[package]
name = "{{project-name}}"
version = "0.1.0"
authors = ["{{authors}}"]
edition = "2018"
resolver = "2"

[profile.release]
opt-level = "s"

[profile.dev]
debug = true # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[features]
native = ["esp-idf-sys/native"]

[dependencies]
{% if std %}esp-idf-sys = { version = "0.27", features = ["binstart"] }
{% else %}log = { version = "0.4", default-features = false }
esp-idf-sys = { version = "0.27", default-features = false, features = ["binstart", "panic_handler", "alloc_handler"] }
esp-idf-svc = { version = "0.32", default-features = false, features = ["alloc"] }{% endif %}

[build-dependencies]
embuild = "0.25"
anyhow = "1"
