[template]
cargo_generate_version = ">=0.10.0"
ignore = [
    ".git",
    ".github",
    "README.md",
]

[placeholders]
mcu = { type = "string", prompt = "MCU", choices = ["esp32", "esp32s2", "esp32s3", "esp32c3"], default = "esp32" }
toolchain = { type = "string", prompt = "Rust toolchain (beware: nightly works only for esp32c3!)", choices = ["esp", "nightly"], default = "esp" }
std = { type = "bool", prompt = "STD support", default = true }
espidfver = { type = "string", prompt = "ESP-IDF native build version (stable = 4.3, upcoming = 4.4, master = 5.0; applicable only with `cargo build --features native`)", choices = ["stable", "upcoming", "master"], default = "stable" }
