[template]
cargo_generate_version = ">=0.10.0"
ignore = [
    ".git",
    ".github",
    "README.md",
]

[placeholders.mcu]
type = "string"
prompt = "MCU"
choices = ["esp32", "esp32s2", "esp32s3", "esp32c3"]
default = "esp32"

[placeholders.toolchain]
type = "string"
prompt = "Rust toolchain (beware: nightly works only for esp32c3!)"
choices = ["esp", "nightly"]
default = "esp"

[placeholders.espidfver]
type = "string"
prompt = "ESP-IDF version (applicable only when building with `cargo build --features native`)"
choices = ["stable", "master"]
default = "stable"
