[package]
name = "{{project-name}}"
version = "0.1.0"
authors = ["{{authors}}"]
edition = "2018"
rust = "1.55"

[features]
native = ["esp-idf-sys/native"]

[dependencies]
esp-idf-sys = { version = "0.21.1", features = ["binstart"] }

[build-dependencies]
embuild = "0.24.5"
anyhow = "1"
